version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose React client on port 3000
    environment:
      REACT_APP_API_URL: "http://localhost:3001" # Replace with your API base URL
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # Expose Node.js server on port 3001
    environment:
      MONGO_URL: "mongodb://root:password@mongo:27017/mern_database?authSource=admin" 
      JWT_SECRET: "12345"
      PORT: 3001
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017" # Expose MongoDB on port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
