apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: social-media-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: yhimanshu075/backend:latest  # Replace with your actual image
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URL
              value: "mongodb://root:password@mongo-service:27017/mern_database?authSource=admin"
            - name: JWT_SECRET
              value: "12345"
            - name: PORT
              value: "3001"
