apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: social-media-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000          # This is the port exposed inside the Kubernetes cluster
      targetPort: 3000    # This is the actual port the frontend is running on
      nodePort: 30000     # Exposes the service on localhost:30000 for local access
  type: NodePort          # Exposes the service outside the cluster on a node port
